# Generated by Django 3.2 on 2021-04-24 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borraccia',
            fields=[
                ('id_borraccia', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('lat_borr', models.DecimalField(decimal_places=14, default=0, max_digits=16)),
                ('lon_borr', models.DecimalField(decimal_places=14, default=0, max_digits=16)),
                ('capacita', models.IntegerField(default=0)),
                ('colore', models.CharField(default=None, max_length=15)),
                ('livello_attuale', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('email_utente', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('lat_utente', models.DecimalField(decimal_places=14, max_digits=16)),
                ('lon_utente', models.DecimalField(decimal_places=14, max_digits=16)),
                ('fabbisogno', models.FloatField()),
                ('borraccia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namaka_admin.borraccia')),
            ],
        ),
    ]
