# Generated by Django 3.1.2 on 2021-06-14 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vittorie',
            fields=[
                ('codice_vittoria', models.AutoField(primary_key=True, serialize=False)),
                ('giorno', models.DateField(default=None)),
                ('totale', models.IntegerField(default=0)),
                ('gruppo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('utente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_utente', models.DecimalField(decimal_places=14, max_digits=16, null=True)),
                ('lon_utente', models.DecimalField(decimal_places=14, max_digits=16, null=True)),
                ('fabbisogno', models.FloatField()),
                ('tempo', models.DateTimeField(default=None, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sorso',
            fields=[
                ('id_sorso', models.AutoField(primary_key=True, serialize=False)),
                ('giorno', models.DateField(default=None)),
                ('totale', models.IntegerField(default=0)),
                ('utente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invito',
            fields=[
                ('id_invito', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('stato', models.CharField(choices=[('VISUALIZZATO', 'Visualizzato'), ('NON VISUALIZZATO', 'Non Visualizzato'), ('ACCETTATO', 'Accettato'), ('RIFIUTATO', 'Rifiutato')], default='NON VISUALIZZATO', max_length=20)),
                ('destinatario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gruppo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('mittente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mittente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodiceSconto',
            fields=[
                ('codice_sconto', models.AutoField(primary_key=True, serialize=False)),
                ('valore', models.IntegerField(default=25)),
                ('stato', models.CharField(choices=[('ASSEGNATO', 'Assegnato'), ('NON ASSEGNATO', 'Non Assegnato')], default='NON ASSEGNATO', max_length=20)),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borraccia',
            fields=[
                ('id_borraccia', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('lat_borr', models.DecimalField(decimal_places=14, default=0, max_digits=16)),
                ('lon_borr', models.DecimalField(decimal_places=14, default=0, max_digits=16)),
                ('capacita', models.IntegerField(default=0)),
                ('colore', models.TextField(default=None, max_length=15)),
                ('livello_attuale', models.IntegerField(default=0)),
                ('utente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
