# Generated by Django 3.2 on 2021-05-28 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_utente', models.DecimalField(decimal_places=14, max_digits=16, null=True)),
                ('lon_utente', models.DecimalField(decimal_places=14, max_digits=16, null=True)),
                ('fabbisogno', models.FloatField()),
                ('tempo', models.DateTimeField(default=None, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sorso',
            fields=[
                ('id_sorso', models.AutoField(primary_key=True, serialize=False)),
                ('giorno', models.DateField(default=None)),
                ('totale', models.IntegerField(default=0)),
                ('utente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borraccia',
            fields=[
                ('id_borraccia', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('lat_borr', models.DecimalField(decimal_places=14, default=0, max_digits=16)),
                ('lon_borr', models.DecimalField(decimal_places=14, default=0, max_digits=16)),
                ('capacita', models.IntegerField(default=0)),
                ('colore', models.CharField(default=None, max_length=15)),
                ('livello_attuale', models.IntegerField(default=0)),
                ('utente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
