# Generated by Django 3.1.2 on 2021-06-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaka_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codicesconto',
            name='codice_sconto',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
