# Generated by Django 3.2 on 2021-04-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namaka_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='borraccia',
        ),
        migrations.AddField(
            model_name='borraccia',
            name='utente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='namaka_admin.utente'),
        ),
    ]
