# Generated by Django 3.2 on 2021-05-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaka_admin', '0002_auto_20210424_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
