# Generated by Django 3.1.2 on 2021-06-08 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('namaka_admin', '0002_invito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Vittorie',
            fields=[
                ('codice_vittoria', models.AutoField(primary_key=True, serialize=False)),
                ('giorno', models.DateField(default=None)),
                ('totale', models.IntegerField(default=0)),
                ('gruppo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('utente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
