# Generated by Django 3.2 on 2021-05-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaka_admin', '0003_utente_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='tempo',
            field=models.DateTimeField(default=None),
        ),
    ]
