# Generated by Django 3.1.2 on 2021-06-09 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('namaka_admin', '0003_auto_20210608_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodiceSconto',
            fields=[
                ('codice_sconto', models.AutoField(primary_key=True, serialize=False)),
                ('valore', models.IntegerField(default=0)),
                ('stato', models.CharField(choices=[('ASSEGNATO', 'Assegnato'), ('NON ASSEGNATO', 'Non Assegnato')], default='NON ASSEGNATO', max_length=20)),
                ('utente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
