# Generated by Django 3.1.2 on 2021-06-09 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('namaka_admin', '0004_codicesconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorso',
            name='utente',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
