# Generated by Django 3.2 on 2021-05-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaka_admin', '0005_sorso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorso',
            name='id',
        ),
        migrations.AlterField(
            model_name='sorso',
            name='id_sorso',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
