# Generated by Django 3.2 on 2021-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaka_admin', '0006_auto_20210505_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorso',
            name='totale',
            field=models.IntegerField(default=0),
        ),
    ]
