# Generated by Django 3.2 on 2021-05-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaka_admin', '0007_sorso_totale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorso',
            name='giorno',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='sorso',
            name='id_sorso',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
