# Generated by Django 3.1.2 on 2021-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaka_admin', '0007_auto_20210609_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codicesconto',
            name='valore',
            field=models.IntegerField(default=25),
        ),
    ]
