# Generated by Django 3.1.2 on 2021-05-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaka_admin', '0008_auto_20210505_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='lat_utente',
            field=models.DecimalField(decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='lon_utente',
            field=models.DecimalField(decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='tempo',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
